# Generated by Django 3.0.5 on 2023-02-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_real', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
    ]
