# Generated by Django 3.0.5 on 2023-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_real', '0006_auto_20230221_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Sold', 'Sold')], max_length=20, null=True),
        ),
    ]
