# Generated by Django 3.0.5 on 2023-02-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_real', '0009_auto_20230222_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
